dist: xenial
language: go
jobs:
  include:
    - go: "1.14.x"
    - go: "1.13.x"
    - go: "1.12.x"
      env:
        # needed to enable module support because Travis checks the project out
        # under $GOPATH
        GO111MODULE=on

script:
  - go test -v ./...
  - go build ./cmd/simple-db-bench
  - ./simple-db-bench -kiters 10
